/**
 *                                !!NOTICE!!
 * This file was automatically generated by mkinit.pl, and includes all of
 * the prelude files required by Picrin. PLEASE DO NOT EDIT THIS FILE, changes
 * will be overwritten the next time the script runs.
 */

#include "picrin.h"

void
pic_init_contrib(pic_state *pic)
{
  void pic_init_random(pic_state *);
  void pic_init_regexp(pic_state *);
  pic_init_random(pic);
  pic_init_regexp(pic);
}
