(define-library (picrin big-number)
  (import (scheme base))
  
  (define (bigint-pow a b)
    (if (bigint-less? b 0)
	(make-bigint 1)
	(bigint-pow-positive a b (make-bigint 1))))
  (define (bigint-pow-positive a b sum)
    (if (bigint-less? b 1)
	sum
	(let ((aa (bigint-mul a a)))
	  (if (bigint-equal? (bigint-rem b 2) 0)
	      (bigint-pow-positive aa (bigint-div b 2) sum)
	      (bigint-pow-positive aa (bigint-div b 2) (bigint-mul sum a))))))
  (define (bigint-mul-mod a b mod)
    (if (bigint-less? mod 1)
	(error "mod must be positive")
	(bigint-rem (bigint-mul a b) mod)))
  (define (bigint-pow-mod a b mod)
    (if (bigint-less? b 0)
	(bigint-rem 1 mod)
	(bigint-pow-mod-positive a b (make-bigint 1) mod)))
  (define (bigint-pow-mod-positive a b sum mod)
    (if (bigint-less? b 1)
	sum
	(let ((aa (bigint-mul-mod a a mod)))
	  (if (bigint-equal? (bigint-rem b 2) 0)
	      (bigint-pow-mod-positive aa (bigint-div b 2) sum mod)
	      (bigint-pow-mod-positive aa (bigint-div b 2) (bigint-mul-mod sum a mod) mod)))))
  (export bigint-pow bigint-mul-mod bigint-pow-mod))
